name: update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Update dependencies and commit changes
        run: deno task -q upgrade:commit --summary ../title.txt --report ../body.md
      - name: Check result
        id: result
        uses: andstor/file-existence-action@v2
        with:
          files: ../title.txt, ../body.md
      - name: Read title.txt
        id: title
        if: steps.result.outputs.files_exists == 'true'
        uses: juliangruber/read-file-action@v1
        with:
          path: ../title.txt
      - name: Read body.md
        id: body
        if: steps.result.outputs.files_exists == 'true'
        uses: juliangruber/read-file-action@v1
        with:
          path: ../body.md
      - name: Create a pull request
        if: steps.result.outputs.files_exists == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PA_TOKEN }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: automation/update-dependencies
          title: ${{ steps.title.outputs.content }}
          body: ${{ steps.body.outputs.content }}
          labels: automation
          delete-branch: true
